trigger:
  - main

variables:
  - group: bobbi_force_group_x
  - name: global_variable
    value: 'This is a global varible'    # this is available to all jobs
  - name: secret_varible
    value: $(MY-SECRET)
  - name: real_secret
    value: $(REAL-SECRET)
  - name: MyRunNumber
    value: '1.0.0-CI+$(Build.BuildNumber)'

stages:
  - stage: 'Build'
    displayName: 'build stuff'
    jobs:
    - job: job1
      pool:
        vmImage: 'ubuntu-latest'
      variables:
        job_variable1: 'Varible for job1'    # this is only available in job1
      steps:
      - script: echo 'hello'
      - script: echo $(myRunNumber)
      - bash: echo $(Build.BuildNumber)
      - bash: echo $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
      - bash: echo $(global_variable)
      - bash: echo $(job_variable1)
      - bash: echo $(secret_varible)
      - bash: echo $(Name)
      - bash: echo $(Role)
      - bash: echo $(real_secret)
  - template: templates/deploy.yml
    parameters:
     code: bob
     key: 8
     displayJobName: deploys_to_development
     deployStageName: dev
  - template: templates/deploy.yml
    parameters:
     code: jeffff
     displayJobName: deploys_to_sandbox
     deployStageName: sand