trigger:
  - main

variables:
  - group: bobbi_force_group_x
  - name: global_variable
    value: 'This is a global varible'    # this is available to all jobs
  - name: secret_varible
    value: $(MY-SECRET)
  - name: real_secret
    value: $(REAL-SECRET)

stages:
  - stage: 'Build'
    displayName: 'build stuff'
    jobs:
    - job: job1
      pool:
        vmImage: 'ubuntu-latest'
      variables:
        job_variable1: 'Varible for job1'    # this is only available in job1
      steps:
      - bash: echo $(global_variable)
      - bash: echo $(job_variable1)
      - bash: echo $(secret_varible)
      - bash: echo $(Name)
      - bash: echo $(Role)
      - bash: echo $(real_secret)

  - stage: 'Deploy'
    displayName: 'deploy stuff'
    jobs:
    - job: job2
      pool:
        vmImage: 'ubuntu-latest'
      variables:
        job_variable2: 'Varible for job2'    # this is only available in job2
      steps:
      - bash: echo $(global_variable)
      - bash: echo $(job_variable2)
      - bash: echo $global_variable
      - bash: echo $(secret_varible)