parameters:
- name: code
  type: string

- name: key
  type: int
  default: 7

stages:
  - stage: 'Deploy'
    displayName: 'deploy stuff'
    jobs:
    - job: job2
      pool:
        vmImage: 'ubuntu-latest'
      variables:
        job_variable2: 'Varible for job2'    # this is only available in job2
      steps:
      - bash: echo $(global_variable)
      - bash: echo $(job_variable2)
      - bash: echo $global_variable
      - bash: echo $(secret_varible)
      - bash: echo ${{ paramenters.code }}
      - bash: echo ${{ paramenters.key }}