parameters:
- name: code
  type: string

- name: key
  type: number
  default: 7

- name: displayJobName
  type: string

- name: deployStageName
  type: string

stages:
  - stage: 'Deploy ${{ parameters.deployStageName }}'
    displayName: 'deploy stuff'
    jobs:
    - job: ${{ parameters.displayJobName }}
      pool:
        vmImage: 'ubuntu-latest'
      variables:
        inline_job_variable2: 'Varible for ${{ parameters.displayJobName }}'   # this is only available in job2
      steps:
      - bash: echo $(global_variable)
      - bash: echo $(job_variable2)
      - bash: echo $(secret_varible)
      - bash: echo ${{ parameters.code }}
      - bash: echo ${{ parameters.key }}